### ISSUE TITLE
data.json没有生成 

### ISSUE THREAD

**Issue by xd1997** [isaced/VVTool#1]
F:\>cd F:\dianshang\baobaos

F:\dianshang\baobaos>vvtool run
Start downloading VV compiler.jar...
VV compiler.jar download success.
Start downloading VV config.properties...
VV config.properties download success.
Start build templates...
Error: Invalid or corrupt jarfile F:/dianshang/baobaos/.compiler.jar
All templates build finished.
F:/dianshang/baobaos
Start HTTP server: http://127.0.0.1:7788
  Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
Start Watching...

我是windows 10系统，怎么一直卡到这里动不了了？

**Comment by isaced** [comment]
暂时不支持 Windows

**Comment by xd1997** [comment]
> 暂时不支持 Windows

请问，目前支持那几个系统？

**Comment by isaced** [comment]
目前只在 macOS 平台测试过
